//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bill_Software {
    
    
    public partial class reset_password {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected global::System.Web.UI.WebControls.Panel PanelError;
        
        protected global::System.Web.UI.WebControls.Label lblErrorMsg;
        
        protected global::System.Web.UI.WebControls.Panel PanelOk;
        
        protected global::System.Web.UI.WebControls.Label lblOkMsg;
        
        protected global::System.Web.UI.WebControls.Panel pnlResetForm;
        
        protected global::System.Web.UI.WebControls.TextBox txtUserId;
        
        protected global::System.Web.UI.WebControls.TextBox txtToken;
        
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        
        protected global::System.Web.UI.WebControls.Button btnReset;
        
        protected global::System.Web.UI.WebControls.HyperLink lnkLogin;
    }
}
